set(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT OFF)
set(ASSIMP_BUILD_TESTS OFF)
set(ASSIMP_INSTALL OFF)
set(ASSIMP_BUILD_ASSIMP_VIEW OFF)
set(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT OFF)
set(ASSIMP_NO_EXPORT ON)
set(ASSIMP_INJECT_DEBUG_POSTFIX OFF)

SET (ASSIMP_BUILD_MS3D_IMPORTER OFF)

add_subdirectory(extern/assimp)
