set(SDL_SHARED OFF)
set(SDL_STATIC ON)
set(SDL_TEST_LIBRARY OFF)

set(SDL_CAMERA OFF)
set(SDL_HAPTIC OFF)
set(SDL_HIDAPI OFF)
set(SDL_JOYSTICK OFF)
set(SDL_VIRTUAL_JOYSTICK OFF)
set(SDL_X11_XSCRNSAVER OFF)
set(SDL_X11_XTEST OFF)

add_subdirectory(extern/sdl)

set(HILL_SDL_INCLUDE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/extern/sdl/include")
